apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm/nginx-deployment/
    repoURL: https://github.com/cakraocha/udacity-suse-challenge-2021
    targetRevision: HEAD
