apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  destination:
    namespace: project-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: project/argocd/nginx-manifests
    repoURL: https://github.com/cakraocha/udacity-suse-challenge-2021
    targetRevision: HEAD
  syncPolicy: {}